# Generated by Django 2.0.5 on 2018-05-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='description',
        ),
    ]
