# Generated by Django 2.0.5 on 2018-05-07 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_auto_20180507_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='text',
        ),
    ]
