# Generated by Django 2.0.5 on 2018-05-07 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0005_auto_20180507_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
